INSERT INTO [dbo].[Corporate]
SELECT * FROM
		OPENJSON
--SELECT * INTO [dbo].[Corporate]
--FROM
--		OPENJSON			
			(
					'
					
					'
			)
			WITH 
			(
				[Id] UNIQUEIDENTIFIER '$.Id'
				,[RegistrationNumber] VARCHAR(100) '$.RegistrationNumber'
				,[CompanyName] VARCHAR(100) '$.CompanyName'
				,[EmailAddress] VARCHAR(80) '$.EmailAddress'
				,[MobilePhone] VARCHAR(80) '$.MobilePhone'
				,[BirthDate] Datetime '$.BirthDate'
				,[HomeNumber] VARCHAR(80) '$.HomeNumber'
				,[WorkNumber] VARCHAR(80) '$.WorkNumber'
				,[PhysicalAddressLine1] VARCHAR(100) '$.PhysicalAddress.Line1'
				,[PhysicalAddressLine2] VARCHAR(100) '$.PhysicalAddress.Line2'
				,[PhysicalAddressLine3] VARCHAR(100) '$.PhysicalAddress.Line3'
				,[PhysicalAddressLine4] VARCHAR(100) '$.PhysicalAddress.Line4'
				,[PhysicalAddressCity] VARCHAR(100) '$.PhysicalAddress.City'
				,[PhysicalAddressProvince] VARCHAR(100) '$.PhysicalAddress.Province'
				,[PhysicalAddressSuburb] VARCHAR(100) '$.PhysicalAddress.Suburb'
				,[PhysicalAddressCountryId] VARCHAR(100) '$.PhysicalAddress.Country.Id'
				,[PhysicalAddressCountryName] VARCHAR(100) '$.PhysicalAddress.Country.Name'
				,[PhysicalAddressPostalCode] VARCHAR(100) '$.PhysicalAddress.PostalCode'

				,[PostalAddressLine1] VARCHAR(100) '$.PostalAddress.Line1'
				,[PostalAddressLine2] VARCHAR(100) '$.PostalAddress.Line2'
				,[PostalAddressLine3] VARCHAR(100) '$.PostalAddress.Line3'
				,[PostalAddressLine4] VARCHAR(100) '$.PostalAddress.Line4'
				,[PostalAddressCity] VARCHAR(100) '$.PostalAddress.City'
				,[PostalAddressProvince] VARCHAR(100) '$.PostalAddress.Province'
				,[PostalAddressSuburb] VARCHAR(100) '$.PostalAddress.Suburb'
				,[PostalAddressCountryId] VARCHAR(100) '$.PostalAddress.Country.Id'
				,[PostalAddressCountryName] VARCHAR(100) '$.PostalAddress.Country.Name'
				,[PostalAddressPostalCode] VARCHAR(100) '$.PostalAddress.PostalCode'

				,[CRMNumber] FLOAT '$.CRMNumber'
				,[IFA] UNIQUEIDENTIFIER '$.IFA'
				,[RelationshipManager] UNIQUEIDENTIFIER '$.RelationshipManager'
				,[RelationshipManagerName] VARCHAR(80) '$.RelationshipManagerName'
				,[InvestmanetManager] UNIQUEIDENTIFIER '$.InvestmanetManager'
				,[InvestmanetManagerName] VARCHAR(80) '$.InvestmanetManagerName'
				,[CleintType] INT '$.CleintType'
				,[Status] INT '$.Status'
				,[StatusName] VARCHAR(80) '$.StatusName'				
				,[SARTaxNumber] VARCHAR(80) '$.SARTaxNumber'				
				,[OnboardingStatus] INT '$.OnboardingStatus'
				,[OnboardingStatusName] VARCHAR(80) '$.OnboardingStatusName'
				,[Region] UNIQUEIDENTIFIER '$.Region'
				,[RegionName] VARCHAR(80) '$.RegionName'
				,[SarsTaxNumber] VARCHAR(80) '$.SarsTaxNumber'				
				,[WealthClient] BIT '$.WealthClient'
				,[HealthClient] BIT '$.HealthClient'
				,[SecuritiesClient] BIT '$.SecuritiesClient'
				,[AccountHolder] BIT '$.AccountHolder'
				,[Member] BIT '$.Member'
				,[IsIFA] BIT '$.IsIFA'				
				,[CountryOfResidence] UNIQUEIDENTIFIER '$.CountryOfResidence'
				,[CountryOfResidenceName] VARCHAR(80) '$.CountryOfResidenceName'
				,[SAResident] BIT '$.SAResident'
				,[IFAName] VARCHAR(80) '$.IFAName'
				,[IFAPhoneHome] VARCHAR(80) '$.IFAPhoneHome'
				,[IFAPhonePersonal] VARCHAR(100) '$.IFAPhonePersonal'
				,[IFAEmail] VARCHAR(100) '$.IFAEmail'
				,[RelationshipManagerPhoneHome] VARCHAR(100) '$.RelationshipManagerPhoneHome'
				,[RelationshipManagerPhonePersonal] VARCHAR(100) '$.RelationshipManagerPhonePersonal'
				,[RelationshipManagerEmail] VARCHAR(100) '$.RelationshipManagerEmail'
				,[OwnerName] VARCHAR(100) '$.OwnerName'
				,[OwnerId] UNIQUEIDENTIFIER '$.OwnerId'
				,[FICACompletedAndReviewed] VARCHAR(100) '$.FICACompletedAndReviewed'
				,[FICAStatus] VARCHAR(100) '$.FICAStatus'
				,[FICAStatusId] UNIQUEIDENTIFIER '$.FICAStatusId'
				,[FICAStatusReason] INT '$.FICAStatusReason'
				,[FICAStatusReasonName] VARCHAR(100) '$.FICAStatusReasonName'
				,[NextFicaReviewDate] DATETIME '$.NextFicaReviewDate'
				,[LastFicaReviewDate] DATETIME '$.LastFicaReviewDate'
				,[IsFICAValid] BIT '$.IsFICAValid'
				,[CPAMarketingMaterial] BIT '$.CPAMarketingMaterial'
				,[CPAMarketingDistribution] INT '$.CPAMarketingDistribution'
				,[CPAMarketingDistributionName] VARCHAR(100) '$.CPAMarketingDistributionName'
			)