--INSERT INTO [dbo].[SasfinAccount]
--SELECT * FROM
--		OPENJSON
SELECT * INTO [dbo].[SasfinAccount]
FROM
		OPENJSON
			(
					'
					
					'
			)
			WITH 
			(
				     [Id] UNIQUEIDENTIFIER '$.Id'
    ,[CurrentMarketValue] FLOAT '$.CurrentMarketValue'
    ,[ProviderId] UNIQUEIDENTIFIER '$.ProviderId'
    ,[ProviderName] VARCHAR(100) '$.ProviderName'
    ,[ProductId] UNIQUEIDENTIFIER '$.ProductId'
    ,[ProductName] VARCHAR(100) '$.ProductName'
    ,[Status] INT '$.Status'
    ,[StatusName] VARCHAR(100) '$.StatusName'
    ,[RelationshipManager] UNIQUEIDENTIFIER '$.RelationshipManager'
    ,[RelationshipManagerName] VARCHAR(100) '$.RelationshipManagerName'
    ,[InvestmentManager] UNIQUEIDENTIFIER '$.InvestmentManager'
    ,[InvestmentManagerName] VARCHAR(100) '$.InvestmentManagerName'
    ,[ProductSubCategory] UNIQUEIDENTIFIER '$.ProductSubCategory'
    ,[ProductSubCategoryName] VARCHAR(100) '$.ProductSubCategoryName'
    ,[ProductCategory] UNIQUEIDENTIFIER '$.ProductCategory'
    ,[ProductCategoryName] VARCHAR(100) '$.ProductCategoryName'
    ,[IsUpdateBDAAccountClicked] BIT '$.IsUpdateBDAAccountClicked'
    ,[Isthisanexistingaccount] BIT '$.Isthisanexistingaccount'
    ,[Isstatusupdated] BIT '$.Isstatusupdated'
    ,[IsMigratedFromSSIS] BIT '$.IsMigratedFromSSIS'
    ,[Individual] UNIQUEIDENTIFIER '$.Individual'
    ,[IsTansferringAssetsFromExistingFund] BIT '$.IsTansferringAssetsFromExistingFund'
    ,[IndividualName] VARCHAR(100) '$.IndividualName'
    ,[IFA] UNIQUEIDENTIFIER '$.IFA'
    ,[IFAName] VARCHAR(100) '$.IFAName'
    ,[IFACompany] UNIQUEIDENTIFIER '$.IFACompany'
    ,[IFACompanyName] VARCHAR(100) '$.IFACompanyName'
    ,[HasUserUpdatedSARecordWithoutBDANO] BIT '$.HasUserUpdatedSARecordWithoutBDANO'
    ,[CurrentMVDate] VARCHAR(100) '$.CurrentMVDate'
    ,[CorporateNumber] VARCHAR(100) '$.CorporateNumber'
    ,[Corporate] UNIQUEIDENTIFIER '$.Corporate'
    ,[CorporateName] VARCHAR(100) '$.CorporateName'
    ,[BEEIndicator] BIT '$.BEEIndicator'
    ,[BDAClientId] VARCHAR(100) '$.BDAClientId'
    ,[ProductInBDAFlag] BIT '$.ProductInBDAFlag'
    ,[AccountNumber] VARCHAR(100) '$.AccountNumber'
    ,[StartDate] VARCHAR(100) '$.StartDate'
    ,[MandateType] INT '$.MandateType'
    ,[MandateTypeName] VARCHAR(100) '$.MandateTypeName'
    ,[BranceCode] VARCHAR(100) '$.BranceCode'
    ,[PartnerCode] VARCHAR(100) '$.PartnerCode'
    ,[AdvisorCode] VARCHAR(100) '$.AdvisorCode'
    ,[Reg28] BIT '$.Reg28'
    ,[LifeAssuredSameasPolicyHolder] BIT '$.LifeAssuredSameasPolicyHolder'
    ,[IsSAXOformsent] BIT '$.IsSAXOformsent'
    ,[Isreadytocreatequotation] BIT '$.Isreadytocreatequotation'
    ,[IsQuotationCreated] BIT '$.IsQuotationCreated'
    ,[Ispolicydocumentsent] BIT '$.Ispolicydocumentsent'
    ,[IsOnboardingLinkSentToClient] BIT '$.IsOnboardingLinkSentToClient'
    ,[Ismandateapplicationformsigned] BIT '$.Ismandateapplicationformsigned'
    ,[IsMandateApplicationFormSent] BIT '$.IsMandateApplicationFormSent'
    ,[IsFICAtaskcreated] BIT '$.IsFICAtaskcreated'
    ,[IsFICAtaskcompleted] BIT '$.IsFICAtaskcompleted'
    ,[IsFICARequired] BIT '$.IsFICARequired'

    ,[IsBankDetailsVerified] BIT '$.IsBankDetailsVerified'
    ,[IsReinvested] NVARCHAR(MAX) '$.IsReinvested'
    ,[Reference] VARCHAR(100) '$.Reference'
    ,[PaymentPeriod] VARCHAR(100) '$.PaymentPeriod'
    ,[IncomeValue] FLOAT '$.IncomeValue'
    ,[RiskStrategy] VARCHAR(100) '$.RiskStrategy'
    ,[StatusReason] INT '$.StatusReason'
    ,[StatusReasonName] VARCHAR(100) '$.StatusReasonName'
    ,[RelationshipManagerEmail] VARCHAR(100) '$.RelationshipManagerEmail'
    ,[RelationshipManagerTel] VARCHAR(100) '$.RelationshipManagerTel'
    ,[AdvisorEmail] VARCHAR(100) '$.AdvisorEmail'
    ,[AdvisorTel] VARCHAR(100) '$.AdvisorTel'
    ,[OwnerName] VARCHAR(100) '$.OwnerName'
    ,[OwnerId] UNIQUEIDENTIFIER '$.OwnerId'
    ,[AssetManager] NVARCHAR(MAX) '$.AssetManager'
			)