Select parent_ID,
		max(case when name='PhysicalAddress.Country.Id' then convert(Varchar(50),StringValue) else '' end) as [Id],
		max(case when name='Fullname' then convert(Varchar(50),StringValue) else '' end) as [Fullname],
		max(case when name='IdNumber' then convert(Varchar(50),StringValue) else '' end) as [IdNumber],
		max(case when name='BirthDate' then convert(Varchar(50),StringValue) else '' end) as [BirthDate],
		max(case when name='FICAStatus' then convert(Varchar(max),StringValue) else '' end) as [FICAStatusName],
		max(case when name='Title' then convert(Varchar(50),StringValue) else '' end) as [Title],
		max(case when name='TitleId' then convert(Varchar(50),StringValue) else '' end) as [TitleId],
		max(case when name='Initials' then convert(Varchar(50),StringValue) else '' end) as [Initials],
		max(case when name='Firstname' then convert(Varchar(50),StringValue) else '' end) as [Firstname],
		max(case when name='PreferedName' then convert(Varchar(50),StringValue) else '' end) as [PreferedName],
		max(case when name='Surname' then convert(Varchar(50),StringValue) else '' end) as [Surname],
		max(case when name='FullName' then convert(Varchar(50),StringValue) else '' end) as [FullName],
		max(case when name='Id' then convert(Varchar(50),StringValue) else '' end) as [Id],
		max(case when name='EmailAddress' then convert(Varchar(50),StringValue) else '' end) as [EmailAddress],
		max(case when name='HasMobilePhone' then convert(Varchar(50),StringValue) else '' end) as [HasMobilePhone],
		max(case when name='HasMobilePhone2' then convert(Varchar(50),StringValue) else '' end) as [HasMobilePhone2],
		max(case when name='HasHomePhone' then convert(Varchar(50),StringValue) else '' end) as [HasHomePhone],
		max(case when name='HasHomePhone2' then convert(Varchar(50),StringValue) else '' end) as [HasHomePhone2],
		max(case when name='HasWorkPhone' then convert(Varchar(50),StringValue) else '' end) as [HasWorkPhone],
		max(case when name='HasWorkPhone2' then convert(Varchar(50),StringValue) else '' end) as [HasWorkPhone2],
		max(case when name='MobilePhone' then convert(Varchar(50),StringValue) else '' end) as [MobilePhone],
		max(case when name='MobilePhone2' then convert(Varchar(50),StringValue) else '' end) as [MobilePhone2],
		max(case when name='HomeNumber' then convert(Varchar(50),StringValue) else '' end) as [HomeNumber],
		max(case when name='HomeNumber2' then convert(Varchar(50),StringValue) else '' end) as [HomeNumber2],
		max(case when name='WorkNumber' then convert(Varchar(50),StringValue) else '' end) as [WorkNumber],
		max(case when name='WorkNumber2' then convert(Varchar(50),StringValue) else '' end) as [WorkNumber2]

From parseJSON
(
       '[
  {
    "IdNumber": "8312125342089",
    "BirthDate": "1983-12-12T00:00:00",
    "Title": "Mr",
    "TitleId": "4c506b53-922e-e711-8106-5065f38b95f1",
    "Initials": "T",
    "Firstname": "Trevor",
    "PreferedName": null,
    "Surname": "Noah",
    "FullName": "Trevor Noah",
    "Id": "e0d70f5a-8557-e811-a95f-000d3a2065c5",
    "EmailAddress": "trevor@noah.co.za",
    "HasMobilePhone": true,
    "HasMobilePhone2": null,
    "HasHomePhone": null,
    "HasHomePhone2": null,
    "HasWorkPhone": null,
    "HasWorkPhone2": null,
    "MobilePhone": "0825502222",
    "MobilePhone2": null,
    "HomeNumber": null,
    "HomeNumber2": null,
    "WorkNumber": null,
    "WorkNumber2": null,
    "PhysicalAddress": {
      "Line1": "",
      "Line2": "",
      "Line3": "",
      "Line4": "Scott Street",
      "Suburb": "Waverley",
      "Country": {
        "Id": "7cd5e23b-062f-e711-810b-5065f38be521",
        "Name": "South Africa",
        "Code1": null,
        "Status": 0,
        "StatusName": null,
        "Code2": null,
        "JSEName": null,
        "InternationalCode": null,
        "OwnerName": null,
        "OwnerId": null
      },
      "PostalCode": "2191",
      "City": "Johannesburg",
      "Province": ""
    },
    "PostalAddress": {
      "Line1": "Scott Street",
      "Line2": "",
      "Line3": "",
      "Line4": null,
      "Suburb": "Waverley",
      "Country": {
        "Id": "7cd5e23b-062f-e711-810b-5065f38be521",
        "Name": "South Africa",
        "Code1": null,
        "Status": 0,
        "StatusName": null,
        "Code2": null,
        "JSEName": null,
        "InternationalCode": null,
        "OwnerName": null,
        "OwnerId": null
      },
      "PostalCode": "2191",
      "City": "Johannesburg",
      "Province": ""
    },
    "AccountNumber": null,
    "XPlanNumber": null,
    "CRMNumber": "132342",
    "IFA": null,
    "RelationshipManager": "dd60ff49-f6a4-e711-8113-5065f38a6ad1",
    "RelationshipManagerName": "Duncan Studer",
    "InvestmanetManager": "dd60ff49-f6a4-e711-8113-5065f38a6ad1",
    "InvestmanetManagerName": "Duncan Studer",
    "CleintType": 0,
    "Status": 0,
    "StatusName": "Active",
    "CitizenshipId": "7cd5e23b-062f-e711-810b-5065f38be521",
    "Citizenship": "South Africa",
    "CityOfBirth": null,
    "CountryOfBirth": null,
    "SARTaxNumber": "25001455",
    "Gender": 1,
    "GenderName": "Male",
    "OnboardingStatus": 1,
    "OnboardingStatusName": "In Progress",
    "EmployeeNumber": null,
    "EmployerNumber": null,
    "CountryOfBirthId": null,
    "Region": "ef58d598-8426-e711-8104-5065f38b9561",
    "RegionName": "Pretoria",
    "SarsTaxNumber": "25001455",
    "NationalityId": null,
    "NationalityName": null,
    "WealthClient": false,
    "HealthClient": false,
    "SecuritiesClient": true,
    "AccountHolder": null,
    "Member": false,
    "IsIFA": false,
    "PassportNumber": null,
    "MaritalStatus": 5,
    "MaritalStatusName": "Single",
    "CountryOfResidence": "7cd5e23b-062f-e711-810b-5065f38be521",
    "CountryOfResidenceName": "South Africa",
    "SAResident": true,
    "SourceOfIncome": "Salary",
    "SourceOfFunds": "Salary",
    "IFAName": null,
    "IFAPhoneHome": null,
    "IFAPhonePersonal": null,
    "IFAEmail": null,
    "RelationshipManagerPhoneHome": null,
    "RelationshipManagerPhonePersonal": null,
    "RelationshipManagerEmail": null,
    "OwnerName": null,
    "OwnerId": null,
    "AssetManager": null,
    "AssetManagerName": null,
    "FICACompletedAndReviewed": false,
    "FICAStatus": "KYC Complete",
    "FICAStatusId": "00736f64-8557-e811-a962-000d3a276620",
    "FICAStatusReason": null,
    "FICAStatusReasonName": null,
    "NextFicaReviewDate": null,
    "LastFicaReviewDate": null,
    "IsFICAValid": null,
    "CPAMarketingMaterial": false,
    "CPAMarketingDistribution": null,
    "CPAMarketingDistributionName": null
  }]'
)
where ValueType = 'string' OR ValueType = 'boolean'
group by parent_ID